LIB_DIR=../lib/

all: identify2 getcwd2
 
identify2:
	gcc -o identify2 identify2.c -L$(LIB_DIR) -lt2fs -Wall

getcwd2:
	gcc -o getcwd2 getcwd2.c -L$(LIB_DIR) -lt2fs -Wall

clean:
	rm -rf identify2 getcwd2
